services:
  db:
    image: postgres:13.21-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: salesdb
    ports:
      - "5432:5432"
    volumes:
      - ./tmp:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d salesdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    
  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env    
    command: ["python", "main.py", "--source", "./app/data/raw/daily_sales.csv"]

